name: Deploy

on:
  push:
    branches: [ master, dev, github-workflow-test ]
  release:
    types: [ published ]

jobs:
  build-deploy:
    name: Deploy to demo and dev sites
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2


    - name: Find and Replace version in plugin file
      uses: datamonsters/replace-action@master
      with:
        files: 'anspress-question-answer.php'
        replacements: 'ANSPRESS_RELEASE_VERSION=9999'

    - name: Find and Replace version in readme.txt
      uses: datamonsters/replace-action@master
      with:
        files: 'readme.txt'
        replacements: 'ANSPRESS_RELEASE_VERSION=9999'

    - name: Archive readme
      uses: actions/upload-artifact@v2
      with:
        name: readme
        path: anspress-question-answer.php

    - name: Upload to development site
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.DEV_SFTP_HOST }}
        username: ${{ secrets.DEV_SFTP_USERNAME }}
        password: ${{ secrets.DEV_SFTP_PASSWORD }}
        source: "*"
        target: ${{ secrets.DEV_PLUGIN_PATH }}

  wp-release:
    name: New release on WordPress.org
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find and Replace
      uses: datamonsters/replace-action@v2
      with:
        files: 'readme.txt,anspress-question-answer.php'
        replacements: 'ANSPRESS_RELEASE_VERSION=${{ github.event.release.tag_name }}'
    - name: Build
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: anspress-question-answer
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/anspress-question-answer.zip
        asset_name: anspress-question-answer.zip
        asset_content_type: application/zip